version: '3'
services:
  backend:
    restart: always
    build: ./backend
    container_name: backend
    hostname: meteo-backend
    ports:
      - 8081:8081
    depends_on:
          mysql
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: meteo
      MYSQL_DATABASE: meteo
      MYSQL_USER: meteo
      MYSQL_PASSWORD: meteo
