version: "3"

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: meteo
      MYSQL_PASSWORD: meteo
      MYSQL_DATABASE: meteo
      MYSQL_ROOT_PASSWORD: meteo
  backend:
    restart: always
    build: ./backend
    container_name: backend
    hostname: meteo-backend
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      DB_USER: meteo
      DB_PASSWORD: meteo
      DB_HOST: db
      DB_PORT: 3306
