server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meteo
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop # create, create-drop, update, validate, none
      show_sql: true
      format_sql: true