server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meteo
    username: nandor
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # create, create-drop, update, validate, none
