server:
  servlet:
    context-path: /api
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/meteo
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:""}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop # create, create-drop, update, validate, none
      show_sql: true
      format_sql: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
